### ISSUE TITLE
Doesn't allow concave polygons

### ISSUE THREAD

**Issue by joehopkinson** [Greenzie/boustrophedon_planner#14]
Any attempt to feed in a polygon* that is convex results in the following CGAL error:

[ INFO] [1622994939.809321796]: Decomposing boundary polygon into sub-polygons...
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: ptr_->count > 0
File: /usr/local/include/CGAL/Handle_for.h
Line: 108

[boustrophedon_server-2] process has died...

*Example polygon coordinates:
1.1, -1.0
0.3, -1.0
0.3, 1.7
-0.3, 1.7
-0.3, -1.0
-0.7, -1.0
-0.7, 2.0
1.1, 2.0

Referenced assertion violation in Handle_for.h:

    Handle_for(const Handle_for& h)
      : ptr_(h.ptr_)
    {
	CGAL_assume (ptr_->count > 0);
        ++(ptr_->count);
    }

This error is consistent with all concave polygons I attempt. Any idea why this is happening?

**Comment by weicyingqiaopian** [comment]
Do you know how to integrate into move_base?
