### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by FrGe2016** [Greenzie/boustrophedon_planner#15]
Hi 

I have that cmake error that i do not know how to solve

-- +++ processing catkin package: 'boustrophedon_server'
-- ==> add_subdirectory(boustrophedon_planner/boustrophedon_server)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at boustrophedon_planner/boustrophedon_server/CMakeLists.txt:16 (find_package):
  By not providing "FindCGAL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CGAL", but
  CMake did not find one.

  Could not find a package configuration file provided by "CGAL" with any of
  the following names:

    CGALConfig.cmake
    cgal-config.cmake

  Add the installation prefix of "CGAL" to CMAKE_PREFIX_PATH or set
  "CGAL_DIR" to a directory containing one of the above files.  If "CGAL"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/francois/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/francois/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:5150: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

Thank in advance

Francois

**Comment by esauortiz** [comment]
Have you installed CGAL in your machine? 

Please see https://doc.cgal.org/latest/Manual/usage.html#secgettingcgal

Hope it helps,

Esau

**Comment by FrGe2016** [comment]
Thanks for your reply it did solve that problem.

I have a second problem with the client that i am trying to make to use the
server.

Here is the client and below the error message that i struggling with.

#!/usr/bin/env python



import rospy
import actionlib
from geometry_msgs.msg                              import Point32,
PolygonStamped
from boustrophedon_msgs.msg    import PlanMowingPathAction,
PlanMowingPathResult, PlanMowingPathFeedback, PlanMowingPathActionGoal
import time

rospy.init_node("PolygonPublisher")

# definition of the feedback callback. This will be called when feedback
# is received from the action server
# it just prints a message indicating a new message has been received
def feedback_callback(feedback):
    print("feedback ***********************************")
    print(feedback)

# create the connection to the action server
client = actionlib.SimpleActionClient('/plan_path', PlanMowingPathAction)
# waits until the action server is up and running
client.wait_for_server()

# creates a goal to send to the action server

my_goal=PlanMowingPathActionGoal()

my_goal.header.frame_id = ""
my_goal.header.stamp = rospy.Time.now()

my_goal.goal_id.id = ""
my_goal.goal_id.stamp = rospy.Time.now()

# Enter polygon definition here
******************************************************

my_goal.goal.property.header.frame_id = ""
my_goal.goal.property.header.stamp = rospy.Time.now()


#first point
my_point=Point32()
my_point.x=0.0
my_point.y=0.0
my_point.z=0.0
my_goal.goal.property.polygon.points.append(my_point)

my_point.x=10.0
my_point.y=0.0
my_point.z=0.0
my_goal.goal.property.polygon.points.append(my_point)

my_point.x=0.0
my_point.y=10.0
my_point.z=0.0
my_goal.goal.property.polygon.points.append(my_point)

my_point.x=0.0
my_point.y=10.0
my_point.z=0.0
my_goal.goal.property.polygon.points.append(my_point)



# Enter robot starting point here
**********************************************


my_goal.goal.robot_position.header.frame_id = ""
my_goal.goal.robot_position.header.stamp = rospy.Time.now()
my_goal.goal.robot_position.pose.position.x=0.0
my_goal.goal.robot_position.pose.position.y=0.0

print(my_goal)

#send the goal to the action server
client.send_goal(my_goal, feedback_cb=feedback_callback)

client.wait_for_result()
print('[Result] State: %d'%(client.get_state()))

*********************************************** And the error message fired
when i send the goal to the server ***************************
Traceback (most recent call last):
  File
"/home/francois/catkin_ws/src/boustrophedon_planner/boustrophedon_server/src/plannerClient2.py",
line 76, in <module>
    client.send_goal(my_goal, feedback_cb=feedback_callback)
  File
"/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_client.py",
line 92, in send_goal
    self.gh = self.action_client.send_goal(goal, self._handle_transition,
self._handle_feedback)
  File
"/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/action_client.py",
line 553, in send_goal
    return self.manager.init_goal(goal, transition_cb, feedback_cb)
  File
"/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/action_client.py",
line 466, in init_goal
    self.send_goal_fn(action_goal)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line
882, in publish
    self.impl.publish(data)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line
1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line
152, in serialize_message
    msg.serialize(b)
  File
"/home/francois/catkin_ws/devel/lib/python2.7/dist-packages/boustrophedon_msgs/msg/_PlanMowingPathActionGoal.py",
line 172, in serialize
    buff.write(_get_struct_3I().pack(_x.goal.property.header.seq,
_x.goal.property.header.stamp.secs, _x.goal.property.header.stamp.nsecs))
AttributeError: 'PlanMowingPathActionGoal' object has no attribute
'property'

Thanks in advance for your help

Francois



Le mar. 29 juin 2021, à 05 h 31, esauortiz ***@***.***> a
écrit :

**Comment by esauortiz** [comment]
removing "goal" from "my_goal.goal.<rest of attributes>" might solve your problem. For instance instead of "my_goal.goal.property.header.frame" you should write "my_goal.property.header.frame".

In addition, I think you’ll need to define the frame_ids if you run into an tf2 transform error.

**Comment by FrGe2016** [comment]
If i remove ".goal" everywhere, i get a shorter error message but it is still telling me that the object has no property ?

Traceback (most recent call last):
  File "/home/francois/catkin_ws/src/boustrophedon_planner/boustrophedon_server/src/plannerClient2b.py", line 46, in <module>
    my_goal.property.polygon.points.append(my_point)
AttributeError: 'PlanMowingPathActionGoal' object has no attribute 'property'

**Comment by FrGe2016** [comment]
I closed this issue by accident i still have the problem

**Comment by weicyingqiaopian** [comment]
Do you know how to integrate into move_base?
