### ISSUE TITLE
How to run the package to get the phenomenon？

### ISSUE THREAD

**Issue by Gaoxiaoshi123** [Greenzie/boustrophedon_planner#17]
Your paper and code have benefited me a lot, but I don't know how to run it. I roslaunch the launch node in the server, but I don't seem to see any effect. How can I operate to see the phenomenon in the paper。
Thank you！

**Comment by weicyingqiaopian** [comment]
Do you know how to integrate into move_base?

**Comment by orensbruli** [comment]
Closing this issue.
Archiving the repo.
