### ISSUE TITLE
Error while processing a polygon

### ISSUE THREAD

**Issue by FrGe2016** [Greenzie/boustrophedon_planner#18]
While processing this polygon i get the following error

![Screenshot from 2021-11-09 16-49-43](https://user-images.githubusercontent.com/16846897/141011070-b1f9b778-6e0c-464d-9d1a-0d62a2fcda3c.png)

[ INFO] [1636493628.111111246]: Got Striping Angle from Orientation: 0
Skipping outlining!
[ INFO] [1636493628.117593756]: Decomposing boundary polygon into sub-polygons...
free(): double free detected in tcache 2
[boustrophedon_server-2] process has died [pid 11555, exit code -6, cmd /home/francois/catkin_ws/devel/lib/boustrophedon_server/boustrophedon_planner_server __name:=boustrophedon_server __log:=/home/francois/.ros/log/9f66a5b2-41a4-11ec-bcf7-38d547191d23/boustrophedon_server-2.log].
log file: /home/francois/.ros/log/9f66a5b2-41a4-11ec-bcf7-38d547191d23/boustrophedon_server-2*.log

I have the same problem with this simple polygon

![Screenshot from 2021-11-09 19-52-06](https://user-images.githubusercontent.com/16846897/141029537-00c231f3-0200-4594-b676-919e0fa55547.png)

And a different problem with this other simple polygon

![Screenshot from 2021-11-09 20-09-24](https://user-images.githubusercontent.com/16846897/141031218-ec5dd1f8-5165-4225-95cc-cd6319f84c46.png)

[ INFO] [1636506497.912456973]: Decomposing boundary polygon into sub-polygons...
[boustrophedon_server-4] process has died [pid 24207, exit code -11, cmd /home/francois/catkin_ws/devel/lib/boustrophedon_server/boustrophedon_planner_server __name:=boustrophedon_server __log:=/home/francois/.ros/log/a8436896-41c2-11ec-bcf7-38d547191d23/boustrophedon_server-4.log].
log file: /home/francois/.ros/log/a8436896-41c2-11ec-bcf7-38d547191d23/boustrophedon_server-4*.log

**Comment by PhilipAmadasun** [comment]
@FrGe2016 Hi! I wanted to ask how exactly you even got this to run. There is only one launch file in this package and when I launch it,nothing knows. What was your procedure? Did you just roscore and then run the launch file?

**Comment by weicyingqiaopian** [comment]
![微信截图_20240508110401](https://github.com/Greenzie/boustrophedon_planner/assets/150759172/f9806d9a-df66-4e45-9206-b0f9482eb444)
Thanks for seeing this problem, I use this server-side and client-side generated path results, and the map doesn't work

**Comment by orensbruli** [comment]
Closing this issue.
Archiving the repo.
