### ISSUE TITLE
A little help please!

### ISSUE THREAD

**Issue by bj-neilson** [Greenzie/boustrophedon_planner#7]
Hi Charles,
As per an earlier Slack chat, I'd love to try this planner on my mower.  I doubt will end up being what I use, as I don't need a coverage planner.  I need something a bit different in an orchard environment.
To get this planner going though, could you please make some suggestions?  I'm not the greatest ROS user.  
To begin with, for example, I could draw a polygon in Google Earth and export the KML file.  That contains the points.  I then need to be able to publish the points via a polygon msg to the boustrophedon server.  I also need to publish a starting pose?
The server will then generate a striping plan.  Does it generate a stream of points or a path?  Just thinking on how to turn the output into goals for the global_planner.
Hope you can help! :)

Ta,
Ben

**Comment by weicyingqiaopian** [comment]
Do you know how to integrate into move_base?
