### ISSUE TITLE
CGAL issue

### ISSUE THREAD

**Issue by gkhanacer** [Greenzie/boustrophedon_planner#8]
I've cloned and tried to compile with catkin_make.

There is an error appeared like this:
```

[ 48%] Building CXX object boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/src/boustrophedon_server/striping_planner.cpp.o
In file included from /usr/include/CGAL/Straight_skeleton_items_2.h:22:0,
                 from /usr/include/CGAL/Straight_skeleton_2.h:23,
                 from /usr/include/CGAL/Straight_skeleton_builder_2.h:37,
                 from /usr/include/CGAL/create_straight_skeleton_2.h:23,
                 from /usr/include/CGAL/create_offset_polygons_2.h:23,
                 from /home/gokhan/catkin_ws/src/boustrophedon_planner/boustrophedon_server/src/boustrophedon_server/striping_planner.cpp:1:
/usr/include/CGAL/Straight_skeleton_vertex_base_2.h: In constructor ‘CGAL::Straight_skeleton_vertex_base_base_2<Refs, P, N>::Straight_skeleton_vertex_base_base_2(int)’:
/usr/include/CGAL/Straight_skeleton_vertex_base_2.h:166:14: error: ‘ORIGIN’ was not declared in this scope
     , mP    (ORIGIN) 
              ^
boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/build.make:110: recipe for target 'boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/src/boustrophedon_server/striping_planner.cpp.o' failed
make[2]: *** [boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/src/boustrophedon_server/striping_planner.cpp.o] Error 1
CMakeFiles/Makefile2:26682: recipe for target 'boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/all' failed
make[1]: *** [boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j1" failed

```

How can this problem be solved?

**Comment by RicheyHuang** [comment]
> I've cloned and tried to compile with catkin_make.
> 
> There is an error appeared like this:
> 
> ```
> 
> [ 48%] Building CXX object boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/src/boustrophedon_server/striping_planner.cpp.o
> In file included from /usr/include/CGAL/Straight_skeleton_items_2.h:22:0,
>                  from /usr/include/CGAL/Straight_skeleton_2.h:23,
>                  from /usr/include/CGAL/Straight_skeleton_builder_2.h:37,
>                  from /usr/include/CGAL/create_straight_skeleton_2.h:23,
>                  from /usr/include/CGAL/create_offset_polygons_2.h:23,
>                  from /home/gokhan/catkin_ws/src/boustrophedon_planner/boustrophedon_server/src/boustrophedon_server/striping_planner.cpp:1:
> /usr/include/CGAL/Straight_skeleton_vertex_base_2.h: In constructor ‘CGAL::Straight_skeleton_vertex_base_base_2<Refs, P, N>::Straight_skeleton_vertex_base_base_2(int)’:
> /usr/include/CGAL/Straight_skeleton_vertex_base_2.h:166:14: error: ‘ORIGIN’ was not declared in this scope
>      , mP    (ORIGIN) 
>               ^
> boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/build.make:110: recipe for target 'boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/src/boustrophedon_server/striping_planner.cpp.o' failed
> make[2]: *** [boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/src/boustrophedon_server/striping_planner.cpp.o] Error 1
> CMakeFiles/Makefile2:26682: recipe for target 'boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/all' failed
> make[1]: *** [boustrophedon_planner/boustrophedon_server/CMakeFiles/boustrophedon_planner_server.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> Invoking "make -j1" failed
> ```
> 
> How can this problem be solved?

Hi, I met the same problem, and I solve this simply by including CGAL/Origin.h in Straight_skeleton_vertex_base_2.h. Then it works~

**Comment by seebq** [comment]
Glad to hear.  We aren't using this in our robotic stack due to licensing issues.  But glad to see it being put to use!  

Closing, re-open if the above doesn't solve it.

**Comment by gkhanacer** [comment]
Thank you @RicheyHuang . I also solved the problem by manual installing CGAL.Thank you for insterest in.
https://doc.cgal.org/latest/Manual/usage.html
