### ISSUE TITLE
Always fail to wait for result?

### ISSUE THREAD

**Issue by longylian6** [Greenzie/boustrophedon_planner#9]
Hi, I had write an action client node, but it always fail to wait for result, why?
```cpp
#include <ros/ros.h>
#include <actionlib/client/simple_action_client.h>
#include <actionlib/client/terminal_state.h>
// #include <boustrophedon_msgs/PlanMovingPathAction.h>
#include "boustrophedon_server/boustrophedon_planner_server.h"

int main (int argc, char **argv)
{
  ros::init(argc, argv, "boustrophedon_planner_client_node");

  // create the action client
  // true causes the client to spin its own thread
  actionlib::SimpleActionClient<boustrophedon_msgs::PlanMowingPathAction> ac("plan_path", true);

  ROS_INFO("Waiting for action server to start.");
  // wait for the action server to start
  ac.waitForServer(); //will wait for infinite time

  ROS_INFO("Action server started, sending goal.");
  // send a goal to the action
  boustrophedon_msgs::PlanMowingPathGoal goal;
  geometry_msgs::PolygonStamped property;
  property.header.frame_id = "map";
  geometry_msgs::Point32 point;
  point.z = 0;
  double length = 5;
  point.x = -length;
  point.y = length;
  property.polygon.points.push_back(point);
  point.x = length;
  point.y = length;
  property.polygon.points.push_back(point);
  point.x = length;
  point.y = -length;
  property.polygon.points.push_back(point);
  point.x = -length;
  point.y = -length;
  property.polygon.points.push_back(point);
  point.x = -length;
  point.y = length;
  property.polygon.points.push_back(point);

  geometry_msgs::PoseStamped robot_position;
  robot_position.header.frame_id = "map";
  robot_position.pose.orientation.x = 0;
  robot_position.pose.orientation.y = 0;
  robot_position.pose.orientation.z = 0;
  robot_position.pose.orientation.w = 1;
  robot_position.pose.position.x = 1;
  robot_position.pose.position.y = 1;
  robot_position.pose.position.z = 0;
  
  goal.property = property;
  goal.robot_position = robot_position;
  ac.sendGoal(goal);

  // //wait for the action to return
  bool finished_before_timeout = ac.waitForResult(ros::Duration(30.0));

  if (finished_before_timeout)
  {
    actionlib::SimpleClientGoalState state = ac.getState();
    ROS_INFO("Action finished: %s",state.toString().c_str());
  }
  else
    ROS_INFO("Action did not finish before the time out.");

  //exit
  return 0;
}
```
I use add_executable() in CMakeList.txt, and run the following command after *catkin_make*
```bash
$ roslaunch boustrophedon_server boustrophedon_server.launch
... logging to /home/sysu/.ros/log/6d834cf4-dcff-11ea-92c4-62d947dadec9/roslaunch-sysu-14592.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://sysu:33685/

SUMMARY
========

PARAMETERS
 * /boustrophedon_server/allow_points_outside_boundary: False
 * /boustrophedon_server/enable_half_y_turns: False
 * /boustrophedon_server/enable_stripe_angle_orientation: True
 * /boustrophedon_server/intermediary_separation: 0.0
 * /boustrophedon_server/outline_clockwise: True
 * /boustrophedon_server/outline_layer_count: 0
 * /boustrophedon_server/points_per_turn: 15
 * /boustrophedon_server/publish_path_points: True
 * /boustrophedon_server/publish_polygons: True
 * /boustrophedon_server/repeat_boundary: False
 * /boustrophedon_server/skip_outlines: True
 * /boustrophedon_server/stripe_angle: 0.0
 * /boustrophedon_server/stripe_separation: 1.0
 * /boustrophedon_server/travel_along_boundary: True
 * /boustrophedon_server/turn_start_offset: 0.5
 * /rosdistro: melodic
 * /rosversion: 1.14.7

NODES
  /
    boustrophedon_server (boustrophedon_server/boustrophedon_planner_server)

ROS_MASTER_URI=http://10.152.45.18:11311

process[boustrophedon_server-1]: started with pid [14601]
[ INFO] [1597280911.186913171]: Got Striping Angle from Orientation: 0
Skipping outlining!
[ INFO] [1597280911.297863542]: Decomposing boundary polygon into sub-polygons...
[ INFO] [1597280911.298188815]: Broke the boundary up into 1 sub-polygons
```
In another terminal, run
```bash
$ rosrun boustrophedon_server boustrophedon_planner_client
[ INFO] [1597200759.464738519]: Waiting for action server to start.
[ INFO] [1597200767.914228864]: Action server started, sending goal.
[ INFO] [1597200797.914582982]: Action did not finish before the time out.
```

**Comment by Spwizzard** [comment]
Try removing the 5th point in your goal. It might not like that you have duplicate points at the start and end.

**Comment by longylian6** [comment]
> Try removing the 5th point in your goal. It might not like that you have duplicate points at the start and end.

Hi, thanks for your reply. I try removing the 5th point in goal, but it still fail to wait for result.

**Comment by longylian6** [comment]
> Try removing the 5th point in your goal. It might not like that you have duplicate points at the start and end.

Hi, thanks for your reply. I find the reason that I configure my computer with [multiple machines](http://wiki.ros.org/ROS/Tutorials/MultipleMachines). Now I run ros master in my own computer, and then I can get a result from server.

**Comment by Spwizzard** [comment]
> Hi, thanks for your reply. I find the reason that I configure my computer with [multiple machines](http://wiki.ros.org/ROS/Tutorials/MultipleMachines). Now I run ros master in my own computer, and then I can get a result from server.

Ah, that would make sense. Yeah you have to be careful about making sure your machines can have 2-way communication.

**Comment by huan-robotics** [comment]
Hi , I'm learning this code and want to run it, but get some errors. Can I have your wechat or QQ number for your advice? Thanks a lot !

**Comment by FrGe2016** [comment]
Can you tell show me the modifications made to the CMakeList.txt.
I get compile errors that i can not solve.

**Comment by PhilipAmadasun** [comment]
@Spwizzard  Hi, I'm confused on how to use this package for motion planning and path planning, there is only one launch file in this package, and when I run it, nothing happens. What am I missing?

**Comment by seebq** [comment]
Hey @DistroIII we need to put this open source project up for adoption!  We don't use it anymore.  Was just reading about how to get this one adopted via https://thenewstack.io/what-happens-when-developers-leave-their-open-source-projects/ 

We aren't able to support it, but you're free to use, we just can't support or maintain anymore.  Best of luck!

**Comment by PhilipAmadasun** [comment]
It seems there are some files missing though that would have enabled motion
planning? were there any on the launch files you guys made other than the
one present?

**Comment by Spwizzard** [comment]
No, there are no files missing. This is an action server that only provides the path your robot should take. You will need to make an action client to request the path from the server, and then feed that result into some other node to perform motion control.

**Comment by PhilipAmadasun** [comment]
Ah okay

**Comment by PhilipAmadasun** [comment]
@longylian6 Were you able to get a client to work? I'm having trouble making one.

**Comment by weicyingqiaopian** [comment]
Do you know how to integrate into move_base?
